-- =============================================
-- ĐỒ ÁN HỆ QUẢN TRỊ CSDL NÂNG CAO
-- SCRIPT: CREATEDATABASE.sql (GLOBAL SCHEMA)
-- HỆ THỐNG GIAO DỊCH TÍN DỤNG TECHCOMBANK
-- =============================================

CREATE DATABASE Techcombank_Global;
GO 

USE Techcombank_Global;
GO

-- 1. NHÓM TỔ CHỨC & NHÂN SỰ
CREATE TABLE CHINHANH (
    idChi_Nhanh VARCHAR(20) PRIMARY KEY,
    nameCN NVARCHAR(100) NOT NULL,
    addressCN NVARCHAR(255) NOT NULL,
    FAX_CN VARCHAR(20)
);

CREATE TABLE PHONGBAN (
    idPhong_Ban VARCHAR(20) PRIMARY KEY,
    namePB NVARCHAR(100) NOT NULL,
    scalePB INT,
    organizationPB NVARCHAR(255)
);

CREATE TABLE NHANVIEN (
    idNhan_Vien VARCHAR(20) PRIMARY KEY,
    nameNV NVARCHAR(100) NOT NULL,
    addressNV NVARCHAR(255),
    numberNV VARCHAR(15) UNIQUE NOT NULL,
    emailNV VARCHAR(100) UNIQUE,
    titleNV NVARCHAR(50),
    idPhong_Ban VARCHAR(20),
    FOREIGN KEY (idPhong_Ban) REFERENCES PHONGBAN(idPhong_Ban)
);

-- 2. NHÓM KHÁCH HÀNG & TÀI KHOẢN
CREATE TABLE KHACHHANG (
    idKH VARCHAR(20) PRIMARY KEY,
    nameKH NVARCHAR(100) NOT NULL,
    bornKH DATE,
    addressKH NVARCHAR(255),
    numberKH VARCHAR(15) UNIQUE NOT NULL,
    identifiKH VARCHAR(20) UNIQUE NOT NULL
);

CREATE TABLE TAIKHOAN (
    idTai_Khoan VARCHAR(20) PRIMARY KEY,
    statusTK NVARCHAR(50),
    creditLimit DECIMAL(18,2) DEFAULT 0,
    numberTK VARCHAR(20) UNIQUE NOT NULL,
    openTK DATETIME DEFAULT GETDATE(),
    idKH VARCHAR(20),
    FOREIGN KEY (idKH) REFERENCES KHACHHANG(idKH)
);

-- 3. NHÓM CHÍNH SÁCH & HỢP ĐỒNG TÍN DỤNG
CREATE TABLE LAISUAT (
    idLai_Suat VARCHAR(20) PRIMARY KEY,
    loaiLai_Suat NVARCHAR(50),
    rateLS FLOAT NOT NULL,
    timeLS DATETIME DEFAULT GETDATE()
);

CREATE TABLE LOAI_HOPDONG (
    idLoaiHop_Dong VARCHAR(20) PRIMARY KEY,
    nameLoaiHD NVARCHAR(100) NOT NULL,
    timeLoaiHD DATETIME,
    idLai_Suat VARCHAR(20),
    FOREIGN KEY (idLai_Suat) REFERENCES LAISUAT(idLai_Suat)
);

CREATE TABLE HOPDONG (
    idHop_Dong VARCHAR(50) PRIMARY KEY,
    paytermsHD NVARCHAR(255),
    borrowHD DECIMAL(18,2) NOT NULL,
    timeHD DATETIME DEFAULT GETDATE(),
    idNhan_Vien VARCHAR(20),
    idLoaiHop_Dong VARCHAR(20),
    idKH VARCHAR(20),
    FOREIGN KEY (idNhan_Vien) REFERENCES NHANVIEN(idNhan_Vien),
    FOREIGN KEY (idLoaiHop_Dong) REFERENCES LOAI_HOPDONG(idLoaiHop_Dong),
    FOREIGN KEY (idKH) REFERENCES KHACHHANG(idKH)
);

-- 4. NHÓM KHO QUỸ & ĐỀ NGHỊ
CREATE TABLE PHIEU_DENHGHI (
    idDe_Nghi VARCHAR(20) PRIMARY KEY,
    numDN DECIMAL(18,2) NOT NULL,
    timeDn DATETIME DEFAULT GETDATE(),
    idNhan_Vien VARCHAR(20),
    FOREIGN KEY (idNhan_Vien) REFERENCES NHANVIEN(idNhan_Vien)
);

CREATE TABLE PHIEU_CHUYENKHOAN (
    idChuyen_Khoan VARCHAR(20) PRIMARY KEY,
    sumCK DECIMAL(18,2) NOT NULL,
    timeCK DATETIME DEFAULT GETDATE(),
    idChi_Nhanh VARCHAR(20),
    FOREIGN KEY (idChi_Nhanh) REFERENCES CHINHANH(idChi_Nhanh)
);

CREATE TABLE KHO_QUY (
    idKho VARCHAR(20) PRIMARY KEY,
    nameKho NVARCHAR(100),
    typeKho NVARCHAR(50),
    reserve_fund DECIMAL(18,2) DEFAULT 0,
    idDe_Nghi VARCHAR(20),
    idChuyen_Khoan VARCHAR(20),
    FOREIGN KEY (idDe_Nghi) REFERENCES PHIEU_DENHGHI(idDe_Nghi),
    FOREIGN KEY (idChuyen_Khoan) REFERENCES PHIEU_CHUYENKHOAN(idChuyen_Khoan)
);

CREATE TABLE PHIEU_XUATKHO (
    idXuat_Kho VARCHAR(20) PRIMARY KEY,
    numXK DECIMAL(18,2) NOT NULL,
    timeXK DATETIME DEFAULT GETDATE(),
    idNhan_Vien VARCHAR(20),
    FOREIGN KEY (idNhan_Vien) REFERENCES NHANVIEN(idNhan_Vien)
);

-- 5. NHÓM GIAO DỊCH & THANH TOÁN
CREATE TABLE GIAODICH_TINDUNG (
    idGD VARCHAR(50) PRIMARY KEY,
    timeGD DATETIME DEFAULT GETDATE(),
    typeGD NVARCHAR(50),
    numGD DECIMAL(18,2) NOT NULL,
    feeGD DECIMAL(18,2) DEFAULT 0,
    discountGD DECIMAL(18,2) DEFAULT 0,
    statusGD NVARCHAR(50),
    idNhan_Vien VARCHAR(20),
    idTai_Khoan VARCHAR(20),
    FOREIGN KEY (idNhan_Vien) REFERENCES NHANVIEN(idNhan_Vien),
    FOREIGN KEY (idTai_Khoan) REFERENCES TAIKHOAN(idTai_Khoan)
);

CREATE TABLE PHIEU_THONGBAO (
    idThong_Bao VARCHAR(20) PRIMARY KEY,
    numThong_Bao INT,
    timeThong_Bao DATETIME DEFAULT GETDATE(),
    idKH VARCHAR(20),
    FOREIGN KEY (idKH) REFERENCES KHACHHANG(idKH)
);

CREATE TABLE PHIEU_THANHTOAN (
    idThanh_Toan VARCHAR(20) PRIMARY KEY,
    numThanh_Toan DECIMAL(18,2) NOT NULL,
    timeThanh_Toan DATETIME DEFAULT GETDATE(),
    idKH VARCHAR(20),
    FOREIGN KEY (idKH) REFERENCES KHACHHANG(idKH)
);

CREATE TABLE PHIEU_NHANTIEN (
    idNhan_Tien VARCHAR(20) PRIMARY KEY,
    numNT DECIMAL(18,2) NOT NULL,
    timeNT DATETIME DEFAULT GETDATE(),
    idKH VARCHAR(20),
    FOREIGN KEY (idKH) REFERENCES KHACHHANG(idKH)
);
GO
PRINT 'Tao Database Global Techcombank va 16 bang thanh cong!';